/**
 * Writes or checks a plan. The lock (pmcp.lock) records what this wrote, so a
 * source removed later takes its outputs with it, and a file someone else wrote
 * is never overwritten.
 */

import { createHash } from "node:crypto";
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  readlinkSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, posix } from "node:path";
import { parse } from "smol-toml";

import { backupFiles } from "./backup.js";
import { ANTIGRAVITY_MCP_PLUGIN } from "./mcp.js";
import { HOOK_DIRECTORY } from "./hooks.js";
import { splitFrontmatter } from "./frontmatter.js";
import { splitKeyed, type Output } from "./outputs.js";
import {
  legacyLinks,
  ProjectError,
  RULES_DIR,
  trackedFiles,
} from "./package-rules.js";
import { censusDirs, plan } from "./plan.js";
import type { ProjectSpec } from "./spec.js";

export const LOCK_FILE = "pmcp.lock";
const BEGIN = "# >>> pmcp project (edit pmcp.toml, not this block) >>>";
const END = "# <<< pmcp project <<<";

/** Marks of projectors this one succeeds; their files may be taken over. */
const PREDECESSORS = [
  "by sync-claude-projection.sh",
  "AUTO-GENERATED by scripts/agent/project.mjs",
];

interface LockEntry {
  readonly path: string;
  readonly kind: string;
  readonly target?: string;
}

export interface ProjectResult {
  readonly backup?: string;
  /** 0 done or clean, 2 check found problems, 3 refused to overwrite. */
  readonly code: 0 | 2 | 3;
  readonly problems: readonly string[];
  readonly outputs: number;
  readonly pruned: number;
}

const sha = (text: string) => createHash("sha256").update(text).digest("hex");

function readLock(root: string): LockEntry[] {
  const path = join(root, LOCK_FILE);
  if (!existsSync(path)) return [];
  const lock = JSON.parse(readFileSync(path, "utf8")) as {
    outputs?: LockEntry[];
  };
  return lock.outputs ?? [];
}

function linkOf(abs: string): string | null {
  try {
    return lstatSync(abs).isSymbolicLink() ? readlinkSync(abs) : null;
  } catch {
    return null;
  }
}

const exists = (abs: string) => existsSync(abs) || linkOf(abs) !== null;

function readJson(abs: string): Record<string, unknown> {
  if (!existsSync(abs)) return {};
  let value: unknown;
  try {
    value = JSON.parse(readFileSync(abs, "utf8"));
  } catch {
    throw new ProjectError(
      "Cannot parse native JSON configuration; contents are redacted",
    );
  }
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function getKey(object: unknown, key: readonly string[]): unknown {
  let node = object;
  for (const part of key) {
    if (node === null || typeof node !== "object") return undefined;
    node = (node as Record<string, unknown>)[part];
  }
  return node;
}

function setKey(
  object: Record<string, unknown>,
  key: readonly string[],
  value: unknown,
): void {
  let node = object;
  for (const part of key.slice(0, -1)) {
    const next = node[part];
    if (next === null || typeof next !== "object" || Array.isArray(next)) {
      node[part] = {};
    }
    node = node[part] as Record<string, unknown>;
  }
  node[key[key.length - 1] ?? ""] = value;
}

/** Deletes a key and any parent it leaves empty. */
function deleteKey(
  object: Record<string, unknown>,
  key: readonly string[],
): void {
  const [head, ...rest] = key;
  if (head === undefined || !(head in object)) return;
  if (rest.length === 0) {
    delete object[head];
    return;
  }
  const child = object[head];
  if (child === null || typeof child !== "object") return;
  deleteKey(child as Record<string, unknown>, rest);
  if (Object.keys(child).length === 0) delete object[head];
}

const same = (a: unknown, b: unknown) =>
  JSON.stringify(a) === JSON.stringify(b);

const block = (content: string) => `${BEGIN}\n${content}${END}\n`;

function withoutBlock(text: string): string {
  const start = text.indexOf(BEGIN);
  if (start === -1) return text;
  const end = text.indexOf(END, start);
  if (end === -1) return text;
  const after = text.slice(end + END.length).replace(/^\n/u, "");
  return `${text.slice(0, start).replace(/\n+$/u, "\n")}${after}`;
}

function present(root: string, output: Output): boolean {
  const abs = join(root, "file" in output ? output.file : output.path);
  switch (output.kind) {
    case "link":
      return linkOf(abs) === output.target;
    case "file":
      return (
        existsSync(abs) &&
        linkOf(abs) === null &&
        readFileSync(abs, "utf8") === output.content
      );
    case "json":
      if (
        output.managed &&
        Array.isArray(output.value) &&
        output.value.length === 0
      ) {
        return getKey(readJson(abs), output.key) === undefined;
      }
      return same(getKey(readJson(abs), output.key), output.value);
    case "block":
      return (
        existsSync(abs) &&
        readFileSync(abs, "utf8").includes(block(output.content))
      );
  }
}

function replaceable(
  root: string,
  output: Output,
  owned: Set<string>,
): boolean {
  if (output.kind === "json") {
    if (output.key[0] !== "mcpServers" || owned.has(output.path)) {
      return true;
    }
    const existing = getKey(readJson(join(root, output.file)), output.key);
    return existing === undefined || same(existing, output.value);
  }
  if (output.kind === "block") {
    const absolute = join(root, output.file);
    const text = existsSync(absolute) ? readFileSync(absolute, "utf8") : "";
    const outside = parse(withoutBlock(text));
    const proposed = parse(output.content);
    const existing = objectKeys(outside["mcp_servers"]);
    return !objectKeys(proposed["mcp_servers"]).some((name) =>
      existing.includes(name),
    );
  }
  if (owned.has(output.path)) return true;
  const abs = join(root, output.path);
  if (!exists(abs)) return true;
  const target = linkOf(abs);
  if (target !== null) {
    return output.kind === "link" && target === output.target;
  }
  if (lstatSync(abs).isDirectory()) return false;
  const text = readFileSync(abs, "utf8");
  if (output.kind === "file" && text === output.content) return true;
  return PREDECESSORS.some((mark) => text.includes(mark));
}

function objectKeys(value: unknown): string[] {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return [];
  }
  return Object.keys(value);
}

/** Entries in projected directories, and top-level rules Grok would load, that nothing declares. */
function undeclared(spec: ProjectSpec, outputs: readonly Output[]): string[] {
  const declared = new Set(outputs.map((o) => o.path));
  const found: string[] = [];
  for (const dir of censusDirs(spec)) {
    const abs = join(spec.root, dir);
    if (!existsSync(abs)) continue;
    for (const entry of readdirSync(abs)) {
      const path = `${dir}/${entry}`;
      if (!declared.has(path)) found.push(path);
    }
  }
  const rules = join(spec.root, RULES_DIR);
  if (spec.tools.has("grok") && existsSync(rules)) {
    for (const entry of readdirSync(rules, { withFileTypes: true })) {
      if (entry.isDirectory()) continue;
      found.push(`${RULES_DIR}/${entry.name}`);
    }
  }
  return found.sort();
}

/** paths: globs whose fixed prefix holds no tracked file: a rule that loads nowhere. */
export function deadGlobs(root: string, outputs: readonly Output[]): string[] {
  const rules = outputs.filter(
    (o) =>
      (o.kind === "link" || o.kind === "file") &&
      o.path.startsWith(`${RULES_DIR}/`),
  );
  if (rules.length === 0) return [];
  const tracked = trackedFiles(root, true);
  if (tracked.length === 0) return [];
  const seen = new Set<string>();
  for (const file of tracked) {
    const parts = file.split("/");
    for (let i = 1; i <= parts.length; i += 1)
      seen.add(parts.slice(0, i).join("/"));
  }
  const dead: string[] = [];
  for (const rule of rules) {
    let text: string;
    if (rule.kind === "file") {
      text = rule.content;
    } else if (rule.kind === "link") {
      const abs = join(root, posix.join(posix.dirname(rule.path), rule.target));
      if (!existsSync(abs)) continue;
      text = readFileSync(abs, "utf8");
    } else {
      continue;
    }
    const paths = splitFrontmatter(text).meta["paths"];
    for (const glob of [paths ?? []].flat()) {
      if (typeof glob !== "string") continue;
      const prefix = glob.replace(/\*.*$/u, "").replace(/\/$/u, "");
      if (prefix !== "" && !seen.has(prefix))
        dead.push(`${rule.path}: ${glob}`);
    }
  }
  return dead;
}

function lockEntry(output: Output): Record<string, unknown> {
  switch (output.kind) {
    case "link":
      return { path: output.path, kind: "link", target: output.target };
    case "file":
      return { path: output.path, kind: "file", sha256: sha(output.content) };
    case "json":
      return {
        path: output.path,
        kind: "json",
        sha256: sha(JSON.stringify(output.value)),
        ...(output.managed ? { managed: output.managed } : {}),
      };
    case "block":
      return { path: output.path, kind: "block", sha256: sha(output.content) };
  }
}

export function project(
  spec: ProjectSpec,
  options: { readonly check: boolean },
): ProjectResult {
  const lock = readLock(spec.root);
  const ownedTargets = new Map(
    lock
      .filter((e) => e.kind === "link" && e.target !== undefined)
      .map((e) => [e.path, e.target as string]),
  );
  const outputs = plan(spec, ownedTargets);
  const owned = new Set(lock.map((e) => e.path));
  const planned = new Set(outputs.map((o) => o.path));
  const stale = lock.filter((e) => !planned.has(e.path));

  const jsonPaths = new Set(
    outputs
      .filter((output) => output.kind === "json")
      .map((output) => output.file),
  );
  for (const entry of stale) {
    const keyed = splitKeyed(entry.path);
    if (entry.kind === "json" && keyed) {
      jsonPaths.add(keyed.file);
    }
  }
  for (const path of jsonPaths) {
    readJson(join(spec.root, path));
  }

  if (options.check) {
    const problems = [
      ...outputs
        .filter((o) => !present(spec.root, o))
        .map((o) => `drift: ${o.path}`),
      ...stale.map((e) => `stale: ${e.path}`),
      ...undeclared(spec, outputs).map((p) => `undeclared: ${p}`),
      ...deadGlobs(spec.root, outputs).map((p) => `dead glob: ${p}`),
    ];
    return {
      code: problems.length > 0 ? 2 : 0,
      problems,
      outputs: outputs.length,
      pruned: 0,
    };
  }

  const refused = outputs
    .filter((o) => !replaceable(spec.root, o, owned))
    .map((o) => `refusing to overwrite a file it did not write: ${o.path}`);
  if (refused.length > 0) {
    return { code: 3, problems: refused, outputs: outputs.length, pruned: 0 };
  }

  const mcpPaths = [
    ".mcp.json",
    ".gemini/settings.json",
    ".agents/mcp_config.json",
    `${ANTIGRAVITY_MCP_PLUGIN}/plugin.json`,
    `${ANTIGRAVITY_MCP_PLUGIN}/mcp_config.json`,
    ".codex/config.toml",
    ".grok/config.toml",
  ];
  const changedMcp = outputs.some((output) => {
    if (
      output.kind !== "json" &&
      output.kind !== "block" &&
      output.kind !== "file"
    ) {
      return false;
    }
    const path = output.kind === "file" ? output.path : output.file;
    return mcpPaths.includes(path) && !present(spec.root, output);
  });
  const staleMcp = stale.some((entry) =>
    mcpPaths.includes(splitKeyed(entry.path)?.file ?? ""),
  );
  const hookPaths = [
    ".codex/hooks.json",
    ".gemini/settings.json",
    ".agents/hooks.json",
    ...outputs
      .filter(
        (output) =>
          output.kind === "file" &&
          output.path.startsWith(`${HOOK_DIRECTORY}/`),
      )
      .map((output) => output.path),
    ...stale
      .filter((entry) => entry.path.startsWith(`${HOOK_DIRECTORY}/`))
      .map((entry) => entry.path),
  ];
  const changedHooks =
    outputs.some(
      (output) =>
        ((output.kind === "json" && output.managed !== undefined) ||
          (output.kind === "file" &&
            output.path.startsWith(`${HOOK_DIRECTORY}/`))) &&
        !present(spec.root, output),
    ) || stale.some((entry) => entry.path.startsWith(`${HOOK_DIRECTORY}/`));
  let backup: string | undefined;
  if (changedMcp || staleMcp || changedHooks) {
    backup = backupFiles(spec.root, [
      ...mcpPaths,
      ...(changedHooks ? hookPaths : []),
      LOCK_FILE,
    ]);
  }

  for (const output of outputs) {
    if (output.kind !== "link" && output.kind !== "file") continue;
    if (present(spec.root, output)) continue;
    const abs = join(spec.root, output.path);
    mkdirSync(dirname(abs), { recursive: true });
    rmSync(abs, { force: true, recursive: true });
    if (output.kind === "link") symlinkSync(output.target, abs);
    else writeFileSync(abs, output.content);
  }

  let pruned = 0;
  const jsonFiles = new Map<string, { sets: Output[]; drops: string[][] }>();
  const blockFiles = new Map<string, string | null>();
  for (const output of outputs) {
    if (output.kind === "json") {
      const entry = jsonFiles.get(output.file) ?? { sets: [], drops: [] };
      entry.sets.push(output);
      jsonFiles.set(output.file, entry);
    }
    if (output.kind === "block") blockFiles.set(output.file, output.content);
  }
  for (const entry of stale) {
    const keyed = splitKeyed(entry.path);
    if (keyed && keyed.key.length === 1 && keyed.key[0] === "pmcp") {
      if (!blockFiles.has(keyed.file)) blockFiles.set(keyed.file, null);
    } else if (keyed) {
      const group = jsonFiles.get(keyed.file) ?? { sets: [], drops: [] };
      group.drops.push(keyed.key);
      jsonFiles.set(keyed.file, group);
    } else {
      rmSync(join(spec.root, entry.path), { force: true, recursive: true });
    }
    pruned += 1;
  }

  for (const [file, { sets, drops }] of jsonFiles) {
    const abs = join(spec.root, file);
    const before = readJson(abs);
    const after = structuredClone(before);
    for (const key of drops) deleteKey(after, key);
    for (const output of sets) {
      if (output.kind !== "json") {
        continue;
      }
      if (
        output.managed &&
        Array.isArray(output.value) &&
        output.value.length === 0
      ) {
        deleteKey(after, output.key);
      } else {
        setKey(after, output.key, output.value);
      }
    }
    if (same(before, after)) continue;
    if (!existsSync(abs) && Object.keys(after).length === 0) continue;
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, `${JSON.stringify(after, null, 2)}\n`);
  }

  for (const [file, content] of blockFiles) {
    const abs = join(spec.root, file);
    const before = existsSync(abs) ? readFileSync(abs, "utf8") : "";
    let after = withoutBlock(before);
    if (content !== null) {
      const sep =
        after === "" || after.endsWith("\n\n")
          ? ""
          : after.endsWith("\n")
            ? "\n"
            : "\n\n";
      after = `${after}${sep}${block(content)}`;
    }
    if (after === before) continue;
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, after);
  }

  // Top-level package rule links of the older layout: removed once their file is linked below.
  if (spec.packageRules) {
    const linkedDirs = new Set(
      outputs
        .filter(
          (o) =>
            o.kind === "link" &&
            o.path.startsWith(`${RULES_DIR}/${spec.packageRules?.dir}/`),
        )
        .map((o) =>
          o.kind === "link"
            ? posix.dirname(o.target.replace(/^(\.\.\/)+/u, ""))
            : "",
        ),
    );
    for (const [name, target] of legacyLinks(spec.root)) {
      const abs = join(spec.root, RULES_DIR, `${name}.md`);
      const broken = !existsSync(abs);
      if (!broken && !linkedDirs.has(posix.dirname(target))) continue;
      rmSync(abs, { force: true });
      pruned += 1;
    }
  }

  writeFileSync(
    join(spec.root, LOCK_FILE),
    `${JSON.stringify({ version: 1, outputs: outputs.filter((output) => output.kind !== "json" || output.managed === undefined || output.managed.length > 0).map(lockEntry) }, null, 2)}\n`,
  );
  return {
    code: 0,
    problems: [],
    outputs: outputs.length,
    pruned,
    ...(backup ? { backup } : {}),
  };
}
