/** What the projector writes. A path is unique across a plan and is the lock key. */
export type Output =
  | { readonly kind: "link"; readonly path: string; readonly target: string }
  | { readonly kind: "file"; readonly path: string; readonly content: string }
  /** One key inside a JSON file other content shares. path = file#a.b */
  | {
      readonly kind: "json";
      readonly path: string;
      readonly file: string;
      readonly key: readonly string[];
      readonly value: unknown;
      readonly managed?: readonly unknown[];
    }
  /** A marked block inside a text file other content shares. path = file#pmcp */
  | {
      readonly kind: "block";
      readonly path: string;
      readonly file: string;
      readonly content: string;
    };

export const MARK = "AUTO-GENERATED by pmcp project";

export function jsonOutput(
  file: string,
  key: readonly string[],
  value: unknown,
): Output {
  return { kind: "json", path: `${file}#${key.join(".")}`, file, key, value };
}

export function blockOutput(file: string, content: string): Output {
  return { kind: "block", path: `${file}#pmcp`, file, content };
}

/** Splits a lock path back into file and key, for entries whose source is gone. */
export function splitKeyed(
  path: string,
): { file: string; key: string[] } | null {
  const at = path.indexOf("#");
  if (at === -1) return null;
  return { file: path.slice(0, at), key: path.slice(at + 1).split(".") };
}
